### ISSUE TITLE
sick compiler doesn't automatically copy intercal.runtime.dll to the output folder

### ISSUE THREAD

**Issue by spartanthe** [jawhitti/INTERCAL#3]
Trying to compile INTERCAL programs in separate folder without intercal.runtime.dll fails with error

> E2002 SOME ASSEMBLY REQUIRED
>      CORRECT SOURCE AND RESUBMIT
> 
Workaround:  copy intercal.runtime.dll to the INTERCAL sources folder.
IMHO it should automatically copy required runtime assembly to the output folder if it can't find one there.

**Comment by jawhitti** [comment]
Changes committed to Issue3 branch. I also a verbose mode (-v or -verbose) which might prove helpful if it seems like the compiler is doing the wrong thing.  Please give feedback if issue is fixed and I will merge to master.

**Comment by jawhitti** [comment]
change committed to master.

**Comment by spartanthe** [comment]
I hereby confirm that the issue is fixed, intercal.runtime.dll is automatically copied by cringe.
Thanks for your efforts supporting the vibrant INTERCAL.NET community.

**Comment by jawhitti** [comment]
When I started this project Eric Raymond's compiler 'ick' was the most popular one. In the intervening years a "sick" compiler was created. So I changed the name to avoid name collisions and confusion.
